Welcome to Debian GNU/Linux ${DEBIAN_VERSION}!

This is a Debian installation ${MEDIA_TYPE},
built on ${BUILD_DATE}.


Press ENTER to continue, or press TAB for a
full list of options.


If the system fails to boot with a white screen
which doesn't go away, try: 

install video=ofonly 

The following desktop environments are available:
gnome, kde, xfce and lxde.  The default on this ${MEDIA_TYPE}
is ${DEFAULT_DESKTOP}.
If you prefer a different desktop, append
    "desktop=<your choice>"
e.g. to do an expert install with the xfce desktop
environment, type
    "expert desktop=xfce"
at the "boot:" prompt.
